-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_adopt_right" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "right_type" varchar,
    "right_description" varchar,
    "adopt_time" datetime,
    "adopt_content_num" varchar,
    "income_item_amount_scale" varchar,
    "income_effective_date" datetime,
    "lease_person_flag" varchar,
    "adopt_right_id" varchar,
    "price" varchar,
    "status" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    "subject_id" varchar,
    PRIMARY KEY ("id")
) COMMENT '认养/租凭权益表';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_adopt_right";
