-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_adopt_content_adopt_price" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "adopt_id" varchar,
    "adopt_name" varchar,
    "start_time" datetime,
    "end_time" datetime,
    "adopt_price_fee" varchar,
    "fee_type" varchar,
    "adopt_person_flag" varchar,
    "adopt_right_id" varchar,
    "pay_num" varchar,
    "adopt_total" varchar,
    "adopt_quota" varchar,
    "status" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    "subject_id" varchar,
    PRIMARY KEY ("id")
) COMMENT '认养/租凭价格表';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_adopt_content_adopt_price";
