-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_deliver" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_id" bigint NOT NULL,
    "order_details_id" bigint NOT NULL,
    "purchase_order_number" varchar NOT NULL,
    "delivery_batch" varchar NOT NULL,
    "expected_delivery_time" datetime NOT NULL,
    "actual_delivery" datetime,
    "expected_delivery_count" int NOT NULL,
    "actual_delivery_count" int,
    "company_id" bigint NOT NULL,
    "settlement_time" datetime,
    "settlement_amount" varchar,
    "delivery_status" varchar,
    "shipment_no" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '采购交付表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_deliver";
