-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_activity_session" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "maxattendpeople" varchar,
    "attendpeople" varchar,
    "registrationfee" varchar,
    "activity_id" varchar,
    "starttime" varchar,
    "remarks" varchar,
    "service_id" varchar,
    "start_date" varchar,
    "end_date" datetime,
    "endtime" varchar,
    "bases_id" varchar,
    "status" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    PRIMARY KEY ("id")
) COMMENT '时间排期';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_activity_session";
