-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_inquiry_detail" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "enquiry_id" varchar,
    "commodity_id" bigint NOT NULL,
    "commodity_category_id" bigint NOT NULL,
    "product_specifications_id" bigint,
    "planned_quantity_min" int,
    "planned_quantity_max" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    "user_id" bigint,
    "source_id" bigint,
    PRIMARY KEY ("id")
) COMMENT '采购询价电子表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_inquiry_detail";
