-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_quotation_electronic" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "quotation_id" bigint NOT NULL,
    "quotation_no" varchar NOT NULL,
    "inquiry_id" bigint NOT NULL,
    "commodity_id" bigint NOT NULL,
    "classify_id" bigint NOT NULL,
    "specifications_id" bigint,
    "initial_batch_count" int,
    "unit_price" varchar,
    "purchase_count" int,
    "total_price" varchar,
    "start_time" datetime,
    "end_time" datetime,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '采购报价单电子表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_quotation_electronic";
