-- 将该建表 SQL 语句，添加到 yudao-module-stock-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "stock_inventory_record_detail" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "stock_record_id" bigint NOT NULL,
    "stock_batch_no" varchar NOT NULL,
    "stock_record_detail_id" bigint NOT NULL,
    "type" int,
    "secondary_classification" varchar,
    "goods_id" varchar NOT NULL,
    "goods_number" varchar,
    "goods_name" varchar NOT NULL,
    "goods_type" varchar,
    "packaging_specification_id" bigint,
    "packaging_specification" varchar,
    "packaging_specification_name" varchar,
    "packaging_type" varchar,
    "inventory_front_quantity" int NOT NULL,
    "inventory_after_quantity" int NOT NULL,
    "goods_allocation_id" bigint,
    "goods_allocation_no" varchar,
    "source_to" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    "user_id" bigint NOT NULL,
    "source_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '盘点记录表子表-明细表';

-- 将该删表 SQL 语句，添加到 yudao-module-stock-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "stock_inventory_record_detail";
