export type BaseInfoVO = {
  id: number
  code: string
  name: string
  enterpriseType: string
  enterpriseTypeName: string
  stauts: string
  userTag: string
  userTagName: string
  manageStatus: string
  address: string
  detailedAddress: string
  socialCreditCode: string
  businessCertificatePhoto: string
  legalPerson: string
  legalIdCard: string
  legalIdCardPhoto: string
  registerTime: string
  description: string
  logo: string
  businessLicenseNo: string
  businessLicensePhoto: string
  businessLicenseEndTime: string
  accountName: string
  accountNo: string
  accountIdCard: string
  accountBank: string
  contactName: string
  contactPhone: string
  villagesAreaId: string
  villagesAreaName: string
  areaId: string
  areaName: string
  ruralId: string
  ruralName: string
  enterpriseScale: string
  serviceRange: string
  remarks: string
  source: number
  subjectId: number
}

export type BaseInfoPageReqVO = {
  code: string
  name: string
  enterpriseType: string
  enterpriseTypeName: string
  stauts: string
  userTag: string
  userTagName: string
  manageStatus: string
  address: string
  detailedAddress: string
  socialCreditCode: string
  businessCertificatePhoto: string
  legalPerson: string
  legalIdCard: string
  legalIdCardPhoto: string
  registerTime: string
  description: string
  logo: string
  businessLicenseNo: string
  businessLicensePhoto: string
  businessLicenseEndTime: string
  accountName: string
  accountNo: string
  accountIdCard: string
  accountBank: string
  contactName: string
  contactPhone: string
  villagesAreaId: string
  villagesAreaName: string
  areaId: string
  areaName: string
  ruralId: string
  ruralName: string
  enterpriseScale: string
  serviceRange: string
  remarks: string
  source: number
  subjectId: number
  createTime: string
}

export type BaseInfoExcelReqVO = {
  code: string
  name: string
  enterpriseType: string
  enterpriseTypeName: string
  stauts: string
  userTag: string
  userTagName: string
  manageStatus: string
  address: string
  detailedAddress: string
  socialCreditCode: string
  businessCertificatePhoto: string
  legalPerson: string
  legalIdCard: string
  legalIdCardPhoto: string
  registerTime: string
  description: string
  logo: string
  businessLicenseNo: string
  businessLicensePhoto: string
  businessLicenseEndTime: string
  accountName: string
  accountNo: string
  accountIdCard: string
  accountBank: string
  contactName: string
  contactPhone: string
  villagesAreaId: string
  villagesAreaName: string
  areaId: string
  areaName: string
  ruralId: string
  ruralName: string
  enterpriseScale: string
  serviceRange: string
  remarks: string
  source: number
  subjectId: number
  createTime: string
}