-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_quotation" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "quote_id" bigint NOT NULL,
    "quote_name" varchar NOT NULL,
    "purchaser_id" bigint NOT NULL,
    "enquiry_id" bigint NOT NULL,
    "indate_date" datetime,
    "submit_status" bit,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '采购询价电子表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_quotation";
