package cn.acsm.module.production.tunnel.dal.mysql.info;

import cn.acsm.module.production.tunnel.controller.admin.info.vo.InfoExportReqVO;
import cn.acsm.module.production.tunnel.controller.admin.info.vo.InfoPageReqVO;
import cn.acsm.module.production.tunnel.dal.dataobject.info.InfoDO;
import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.framework.mybatis.core.query.LambdaQueryWrapperX;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 地块信息 Mapper
 *
 * @author 芋道源码
 */
@Mapper
public interface InfoMapper extends BaseMapperX<InfoDO> {

    default List<InfoDO> selectList(InfoPageReqVO reqVO) {
        return selectList( new LambdaQueryWrapperX<InfoDO>()
                .eqIfPresent(InfoDO::getBaseId, reqVO.getBaseId())
                .eqIfPresent(InfoDO::getPartitionId, reqVO.getPartitionId())
                .eqIfPresent(InfoDO::getRealPlantJson, reqVO.getRealPlantJson())
                .eqIfPresent(InfoDO::getTunnelInfoId, reqVO.getTunnelInfoId())
                .likeIfPresent(InfoDO::getTunnelName, reqVO.getTunnelName())
                .eqIfPresent(InfoDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(InfoDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(InfoDO::getAreaNumber, reqVO.getAreaNumber())
                .eqIfPresent(InfoDO::getMuNumber, reqVO.getMuNumber())
                .eqIfPresent(InfoDO::getAreaId, reqVO.getAreaId())
                .eqIfPresent(InfoDO::getBdLongitude, reqVO.getBdLongitude())
                .eqIfPresent(InfoDO::getBdLatitude, reqVO.getBdLatitude())
                .eqIfPresent(InfoDO::getCoordinateGroup, reqVO.getCoordinateGroup())
                .eqIfPresent(InfoDO::getPlantEnvTypeId, reqVO.getPlantEnvTypeId())
                .eqIfPresent(InfoDO::getStaticPicture, reqVO.getStaticPicture())
                .eqIfPresent(InfoDO::getViewColor, reqVO.getViewColor())
                .eqIfPresent(InfoDO::getBorderColor, reqVO.getBorderColor())
                .eqIfPresent(InfoDO::getOpacity, reqVO.getOpacity())
                .eqIfPresent(InfoDO::getLittleStar, reqVO.getLittleStar())
                .eqIfPresent(InfoDO::getLittleType, reqVO.getLittleType())
                .eqIfPresent(InfoDO::getVillagesId, reqVO.getVillagesId())
                .eqIfPresent(InfoDO::getVillagesCode, reqVO.getVillagesCode())
                .eqIfPresent(InfoDO::getRuralId, reqVO.getRuralId())
                .eqIfPresent(InfoDO::getRuralCode, reqVO.getRuralCode())
                .eqIfPresent(InfoDO::getTunnelCode, reqVO.getTunnelCode())
                .eqIfPresent(InfoDO::getOfficeCode, reqVO.getOfficeCode())
                .likeIfPresent(InfoDO::getOfficeName, reqVO.getOfficeName())
                .eqIfPresent(InfoDO::getCompanyCode, reqVO.getCompanyCode())
                .likeIfPresent(InfoDO::getCompanyName, reqVO.getCompanyName())
                .eqIfPresent(InfoDO::getRemarks, reqVO.getRemarks())
                .eqIfPresent(InfoDO::getReviewStatus, reqVO.getReviewStatus())
                .eqIfPresent(InfoDO::getReviewer, reqVO.getReviewer())
                .betweenIfPresent(InfoDO::getReviewDate, reqVO.getReviewDate())
                .eqIfPresent(InfoDO::getReviewContent, reqVO.getReviewContent())
                .eqIfPresent(InfoDO::getArchiveStatus, reqVO.getArchiveStatus())
                .betweenIfPresent(InfoDO::getArchiveTime, reqVO.getArchiveTime())
                .eqIfPresent(InfoDO::getCorpCode, reqVO.getCorpCode())
                .likeIfPresent(InfoDO::getCorpName, reqVO.getCorpName())
                .eqIfPresent(InfoDO::getSyncStatus, reqVO.getSyncStatus())
                .eqIfPresent(InfoDO::getFarmers, reqVO.getFarmers())
                .eqIfPresent(InfoDO::getInstructors, reqVO.getInstructors())
                .likeIfPresent(InfoDO::getFarmersName, reqVO.getFarmersName())
                .likeIfPresent(InfoDO::getInstructorsName, reqVO.getInstructorsName())
                .eqIfPresent(InfoDO::getOldId, reqVO.getOldId())
                .likeIfPresent(InfoDO::getAreaName, reqVO.getAreaName())
                .likeIfPresent(InfoDO::getRuralName, reqVO.getRuralName())
                .likeIfPresent(InfoDO::getVillagesName, reqVO.getVillagesName())
                .eqIfPresent(InfoDO::getPerformId, reqVO.getPerformId())
                .eqIfPresent(InfoDO::getDepartmentId, reqVO.getDepartmentId())
                .eqIfPresent(InfoDO::getMakersId, reqVO.getMakersId())
                .eqIfPresent(InfoDO::getMakersDepartmentId, reqVO.getMakersDepartmentId())
                .eqIfPresent(InfoDO::getSubjectId, reqVO.getSubjectId())
                .eqIfPresent(InfoDO::getAreaNumUnit, reqVO.getAreaNumUnit())
                .eqIfPresent(InfoDO::getAreaLocation, reqVO.getAreaLocation())
                .eqIfPresent(InfoDO::getLableIds, reqVO.getLableIds())
                .eqIfPresent(InfoDO::getPlantStatus, reqVO.getPlantStatus())
                .eqIfPresent(InfoDO::getTunnelinfoImage, reqVO.getTunnelinfoImage())
                .eqIfPresent(InfoDO::getPlantAmount, reqVO.getPlantAmount())
                .eqIfPresent(InfoDO::getAdoption, reqVO.getAdoption())
                .betweenIfPresent(InfoDO::getCreateTime, reqVO.getCreateTime())
                .eqIfPresent(InfoDO::getSource, reqVO.getSource())
                .orderByDesc(InfoDO::getId));
    }

    default PageResult<InfoDO> selectPage(InfoPageReqVO reqVO) {
        return selectPage(reqVO, new LambdaQueryWrapperX<InfoDO>()
                .eqIfPresent(InfoDO::getBaseId, reqVO.getBaseId())
                .eqIfPresent(InfoDO::getPartitionId, reqVO.getPartitionId())
                .eqIfPresent(InfoDO::getRealPlantJson, reqVO.getRealPlantJson())
                .eqIfPresent(InfoDO::getTunnelInfoId, reqVO.getTunnelInfoId())
                .likeIfPresent(InfoDO::getTunnelName, reqVO.getTunnelName())
                .eqIfPresent(InfoDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(InfoDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(InfoDO::getAreaNumber, reqVO.getAreaNumber())
                .eqIfPresent(InfoDO::getMuNumber, reqVO.getMuNumber())
                .eqIfPresent(InfoDO::getAreaId, reqVO.getAreaId())
                .eqIfPresent(InfoDO::getBdLongitude, reqVO.getBdLongitude())
                .eqIfPresent(InfoDO::getBdLatitude, reqVO.getBdLatitude())
                .eqIfPresent(InfoDO::getCoordinateGroup, reqVO.getCoordinateGroup())
                .eqIfPresent(InfoDO::getPlantEnvTypeId, reqVO.getPlantEnvTypeId())
                .eqIfPresent(InfoDO::getStaticPicture, reqVO.getStaticPicture())
                .eqIfPresent(InfoDO::getViewColor, reqVO.getViewColor())
                .eqIfPresent(InfoDO::getBorderColor, reqVO.getBorderColor())
                .eqIfPresent(InfoDO::getOpacity, reqVO.getOpacity())
                .eqIfPresent(InfoDO::getLittleStar, reqVO.getLittleStar())
                .eqIfPresent(InfoDO::getLittleType, reqVO.getLittleType())
                .eqIfPresent(InfoDO::getVillagesId, reqVO.getVillagesId())
                .eqIfPresent(InfoDO::getVillagesCode, reqVO.getVillagesCode())
                .eqIfPresent(InfoDO::getRuralId, reqVO.getRuralId())
                .eqIfPresent(InfoDO::getRuralCode, reqVO.getRuralCode())
                .eqIfPresent(InfoDO::getTunnelCode, reqVO.getTunnelCode())
                .eqIfPresent(InfoDO::getOfficeCode, reqVO.getOfficeCode())
                .likeIfPresent(InfoDO::getOfficeName, reqVO.getOfficeName())
                .eqIfPresent(InfoDO::getCompanyCode, reqVO.getCompanyCode())
                .likeIfPresent(InfoDO::getCompanyName, reqVO.getCompanyName())
                .eqIfPresent(InfoDO::getRemarks, reqVO.getRemarks())
                .eqIfPresent(InfoDO::getReviewStatus, reqVO.getReviewStatus())
                .eqIfPresent(InfoDO::getReviewer, reqVO.getReviewer())
                .betweenIfPresent(InfoDO::getReviewDate, reqVO.getReviewDate())
                .eqIfPresent(InfoDO::getReviewContent, reqVO.getReviewContent())
                .eqIfPresent(InfoDO::getArchiveStatus, reqVO.getArchiveStatus())
                .betweenIfPresent(InfoDO::getArchiveTime, reqVO.getArchiveTime())
                .eqIfPresent(InfoDO::getCorpCode, reqVO.getCorpCode())
                .likeIfPresent(InfoDO::getCorpName, reqVO.getCorpName())
                .eqIfPresent(InfoDO::getSyncStatus, reqVO.getSyncStatus())
                .eqIfPresent(InfoDO::getFarmers, reqVO.getFarmers())
                .eqIfPresent(InfoDO::getInstructors, reqVO.getInstructors())
                .likeIfPresent(InfoDO::getFarmersName, reqVO.getFarmersName())
                .likeIfPresent(InfoDO::getInstructorsName, reqVO.getInstructorsName())
                .eqIfPresent(InfoDO::getOldId, reqVO.getOldId())
                .likeIfPresent(InfoDO::getAreaName, reqVO.getAreaName())
                .likeIfPresent(InfoDO::getRuralName, reqVO.getRuralName())
                .likeIfPresent(InfoDO::getVillagesName, reqVO.getVillagesName())
                .eqIfPresent(InfoDO::getPerformId, reqVO.getPerformId())
                .eqIfPresent(InfoDO::getDepartmentId, reqVO.getDepartmentId())
                .eqIfPresent(InfoDO::getMakersId, reqVO.getMakersId())
                .eqIfPresent(InfoDO::getMakersDepartmentId, reqVO.getMakersDepartmentId())
                .eqIfPresent(InfoDO::getSubjectId, reqVO.getSubjectId())
                .eqIfPresent(InfoDO::getAreaNumUnit, reqVO.getAreaNumUnit())
                .eqIfPresent(InfoDO::getAreaLocation, reqVO.getAreaLocation())
                .eqIfPresent(InfoDO::getLableIds, reqVO.getLableIds())
                .eqIfPresent(InfoDO::getPlantStatus, reqVO.getPlantStatus())
                .eqIfPresent(InfoDO::getTunnelinfoImage, reqVO.getTunnelinfoImage())
                .eqIfPresent(InfoDO::getPlantAmount, reqVO.getPlantAmount())
                .eqIfPresent(InfoDO::getAdoption, reqVO.getAdoption())
                .betweenIfPresent(InfoDO::getCreateTime, reqVO.getCreateTime())
                .eqIfPresent(InfoDO::getSource, reqVO.getSource())
                .orderByDesc(InfoDO::getId));
    }

    default List<InfoDO> selectList(InfoExportReqVO reqVO) {
        return selectList(new LambdaQueryWrapperX<InfoDO>()
                .eqIfPresent(InfoDO::getBaseId, reqVO.getBaseId())
                .eqIfPresent(InfoDO::getPartitionId, reqVO.getPartitionId())
                .eqIfPresent(InfoDO::getRealPlantJson, reqVO.getRealPlantJson())
                .eqIfPresent(InfoDO::getTunnelInfoId, reqVO.getTunnelInfoId())
                .likeIfPresent(InfoDO::getTunnelName, reqVO.getTunnelName())
                .eqIfPresent(InfoDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(InfoDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(InfoDO::getAreaNumber, reqVO.getAreaNumber())
                .eqIfPresent(InfoDO::getMuNumber, reqVO.getMuNumber())
                .eqIfPresent(InfoDO::getAreaId, reqVO.getAreaId())
                .eqIfPresent(InfoDO::getBdLongitude, reqVO.getBdLongitude())
                .eqIfPresent(InfoDO::getBdLatitude, reqVO.getBdLatitude())
                .eqIfPresent(InfoDO::getCoordinateGroup, reqVO.getCoordinateGroup())
                .eqIfPresent(InfoDO::getPlantEnvTypeId, reqVO.getPlantEnvTypeId())
                .eqIfPresent(InfoDO::getStaticPicture, reqVO.getStaticPicture())
                .eqIfPresent(InfoDO::getViewColor, reqVO.getViewColor())
                .eqIfPresent(InfoDO::getBorderColor, reqVO.getBorderColor())
                .eqIfPresent(InfoDO::getOpacity, reqVO.getOpacity())
                .eqIfPresent(InfoDO::getLittleStar, reqVO.getLittleStar())
                .eqIfPresent(InfoDO::getLittleType, reqVO.getLittleType())
                .eqIfPresent(InfoDO::getVillagesId, reqVO.getVillagesId())
                .eqIfPresent(InfoDO::getVillagesCode, reqVO.getVillagesCode())
                .eqIfPresent(InfoDO::getRuralId, reqVO.getRuralId())
                .eqIfPresent(InfoDO::getRuralCode, reqVO.getRuralCode())
                .eqIfPresent(InfoDO::getTunnelCode, reqVO.getTunnelCode())
                .eqIfPresent(InfoDO::getOfficeCode, reqVO.getOfficeCode())
                .likeIfPresent(InfoDO::getOfficeName, reqVO.getOfficeName())
                .eqIfPresent(InfoDO::getCompanyCode, reqVO.getCompanyCode())
                .likeIfPresent(InfoDO::getCompanyName, reqVO.getCompanyName())
                .eqIfPresent(InfoDO::getRemarks, reqVO.getRemarks())
                .eqIfPresent(InfoDO::getReviewStatus, reqVO.getReviewStatus())
                .eqIfPresent(InfoDO::getReviewer, reqVO.getReviewer())
                .betweenIfPresent(InfoDO::getReviewDate, reqVO.getReviewDate())
                .eqIfPresent(InfoDO::getReviewContent, reqVO.getReviewContent())
                .eqIfPresent(InfoDO::getArchiveStatus, reqVO.getArchiveStatus())
                .betweenIfPresent(InfoDO::getArchiveTime, reqVO.getArchiveTime())
                .eqIfPresent(InfoDO::getCorpCode, reqVO.getCorpCode())
                .likeIfPresent(InfoDO::getCorpName, reqVO.getCorpName())
                .eqIfPresent(InfoDO::getSyncStatus, reqVO.getSyncStatus())
                .eqIfPresent(InfoDO::getFarmers, reqVO.getFarmers())
                .eqIfPresent(InfoDO::getInstructors, reqVO.getInstructors())
                .likeIfPresent(InfoDO::getFarmersName, reqVO.getFarmersName())
                .likeIfPresent(InfoDO::getInstructorsName, reqVO.getInstructorsName())
                .eqIfPresent(InfoDO::getOldId, reqVO.getOldId())
                .likeIfPresent(InfoDO::getAreaName, reqVO.getAreaName())
                .likeIfPresent(InfoDO::getRuralName, reqVO.getRuralName())
                .likeIfPresent(InfoDO::getVillagesName, reqVO.getVillagesName())
                .eqIfPresent(InfoDO::getPerformId, reqVO.getPerformId())
                .eqIfPresent(InfoDO::getDepartmentId, reqVO.getDepartmentId())
                .eqIfPresent(InfoDO::getMakersId, reqVO.getMakersId())
                .eqIfPresent(InfoDO::getMakersDepartmentId, reqVO.getMakersDepartmentId())
                .eqIfPresent(InfoDO::getSubjectId, reqVO.getSubjectId())
                .eqIfPresent(InfoDO::getAreaNumUnit, reqVO.getAreaNumUnit())
                .eqIfPresent(InfoDO::getAreaLocation, reqVO.getAreaLocation())
                .eqIfPresent(InfoDO::getLableIds, reqVO.getLableIds())
                .eqIfPresent(InfoDO::getPlantStatus, reqVO.getPlantStatus())
                .eqIfPresent(InfoDO::getTunnelinfoImage, reqVO.getTunnelinfoImage())
                .eqIfPresent(InfoDO::getPlantAmount, reqVO.getPlantAmount())
                .eqIfPresent(InfoDO::getAdoption, reqVO.getAdoption())
                .betweenIfPresent(InfoDO::getCreateTime, reqVO.getCreateTime())
                .eqIfPresent(InfoDO::getSource, reqVO.getSource())
                .orderByDesc(InfoDO::getId));
    }

}
