-- 将该建表 SQL 语句，添加到 yudao-module-sales-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "sales_commodity" (
    "id" varchar NOT NULL,
    "commodity_code" varchar,
    "article_no" varchar,
    "commodity_bar_code" varchar,
    "commodity_name" varchar,
    "type" bit,
    "sort" int,
    "key_word" varchar,
    "manufacturer" varchar,
    "batch" varchar,
    "available_num" int,
    "provider_name" varchar,
    "provider_id" varchar,
    "old_provider_id" varchar,
    "spec_num" varchar,
    "lable_ids" varchar,
    "warn_stock_num" bigint,
    "weight_unit" varchar,
    "package_unit" varchar,
    "commodity_category_id" varchar,
    "manufacturer_name" varchar,
    "wholesale_price" varchar,
    "retail_price" varchar,
    "stock_num" bigint,
    "sale_state" varchar,
    "introduction" varchar,
    "trace_status" varchar,
    "plant_id" varchar,
    "commodity_plant_id" varchar,
    "sell_type" varchar,
    "add_type" varchar,
    "address" varchar,
    "num" varchar,
    "sync_status" varchar,
    "arrive_date" datetime,
    "commodity_type" varchar,
    "commodity_img" varchar,
    "publicity_price" varchar,
    "production_address" varchar,
    "origin_place" varchar,
    "ant_name" varchar,
    "create_id" varchar,
    "video_url" varchar,
    "status" int NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '商品';

-- 将该删表 SQL 语句，添加到 yudao-module-sales-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "sales_commodity";
