-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_adopt_content_health" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "adopt_content_id" varchar,
    "type" varchar,
    "assessment" datetime,
    "assessmenter" varchar,
    "assessment_result" varchar,
    "description" varchar,
    "company_name" varchar,
    "status" int NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    "subject_id" varchar,
    PRIMARY KEY ("id")
) COMMENT '服务资源-认养物/租凭物就医记录';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_adopt_content_health";
