package cn.acsm.module.production.devices.dal.mysql.info;

import java.util.*;

import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.mybatis.core.query.LambdaQueryWrapperX;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.acsm.module.production.devices.dal.dataobject.info.InfoDO;
import org.apache.ibatis.annotations.Mapper;
import cn.acsm.module.production.devices.controller.admin.info.vo.*;

/**
 * 设备 Mapper
 *
 * @author 芋道源码
 */
@Mapper
public interface InfoMapper extends BaseMapperX<InfoDO> {

    default PageResult<InfoDO> selectPage(InfoPageReqVO reqVO) {
        return selectPage(reqVO, new LambdaQueryWrapperX<InfoDO>()
                .eqIfPresent(InfoDO::getBaseId, reqVO.getBaseId())
                .eqIfPresent(InfoDO::getTunnelId, reqVO.getTunnelId())
                .eqIfPresent(InfoDO::getFacilitysId, reqVO.getFacilitysId())
                .likeIfPresent(InfoDO::getDeviceName, reqVO.getDeviceName())
                .eqIfPresent(InfoDO::getDeviceSn, reqVO.getDeviceSn())
                .eqIfPresent(InfoDO::getClassify, reqVO.getClassify())
                .eqIfPresent(InfoDO::getDeviceType, reqVO.getDeviceType())
                .likeIfPresent(InfoDO::getDeviceTypeName, reqVO.getDeviceTypeName())
                .eqIfPresent(InfoDO::getBuyer, reqVO.getBuyer())
                .betweenIfPresent(InfoDO::getBuyTime, reqVO.getBuyTime())
                .eqIfPresent(InfoDO::getProductBy, reqVO.getProductBy())
                .eqIfPresent(InfoDO::getProductModel, reqVO.getProductModel())
                .eqIfPresent(InfoDO::getPower, reqVO.getPower())
                .eqIfPresent(InfoDO::getWorkStatus, reqVO.getWorkStatus())
                .eqIfPresent(InfoDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(InfoDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(InfoDO::getParamDeviceIp, reqVO.getParamDeviceIp())
                .eqIfPresent(InfoDO::getParamHttpPort, reqVO.getParamHttpPort())
                .eqIfPresent(InfoDO::getParamDevicePort, reqVO.getParamDevicePort())
                .eqIfPresent(InfoDO::getParamRtspPort, reqVO.getParamRtspPort())
                .likeIfPresent(InfoDO::getParamDeviceUsername, reqVO.getParamDeviceUsername())
                .eqIfPresent(InfoDO::getParamDevicePassword, reqVO.getParamDevicePassword())
                .eqIfPresent(InfoDO::getParamChanelNum, reqVO.getParamChanelNum())
                .eqIfPresent(InfoDO::getParamYsyUrl, reqVO.getParamYsyUrl())
                .eqIfPresent(InfoDO::getParamYsyUrlHd, reqVO.getParamYsyUrlHd())
                .eqIfPresent(InfoDO::getParamStreamType, reqVO.getParamStreamType())
                .eqIfPresent(InfoDO::getOfficeCode, reqVO.getOfficeCode())
                .likeIfPresent(InfoDO::getOfficeName, reqVO.getOfficeName())
                .eqIfPresent(InfoDO::getCompanyCode, reqVO.getCompanyCode())
                .likeIfPresent(InfoDO::getCompanyName, reqVO.getCompanyName())
                .eqIfPresent(InfoDO::getRemarks, reqVO.getRemarks())
                .eqIfPresent(InfoDO::getReviewStatus, reqVO.getReviewStatus())
                .eqIfPresent(InfoDO::getReviewer, reqVO.getReviewer())
                .betweenIfPresent(InfoDO::getReviewDate, reqVO.getReviewDate())
                .eqIfPresent(InfoDO::getReviewContent, reqVO.getReviewContent())
                .eqIfPresent(InfoDO::getIsopen, reqVO.getIsopen())
                .eqIfPresent(InfoDO::getKingViewUrl, reqVO.getKingViewUrl())
                .eqIfPresent(InfoDO::getIsMobile, reqVO.getIsMobile())
                .eqIfPresent(InfoDO::getCorpCode, reqVO.getCorpCode())
                .likeIfPresent(InfoDO::getCorpName, reqVO.getCorpName())
                .betweenIfPresent(InfoDO::getServiceDate, reqVO.getServiceDate())
                .eqIfPresent(InfoDO::getSyncStatus, reqVO.getSyncStatus())
                .eqIfPresent(InfoDO::getIsbeta, reqVO.getIsbeta())
                .eqIfPresent(InfoDO::getOldId, reqVO.getOldId())
                .eqIfPresent(InfoDO::getIotProductKey, reqVO.getIotProductKey())
                .likeIfPresent(InfoDO::getIotDeviceName, reqVO.getIotDeviceName())
                .likeIfPresent(InfoDO::getIotProductName, reqVO.getIotProductName())
                .eqIfPresent(InfoDO::getIotIotId, reqVO.getIotIotId())
                .eqIfPresent(InfoDO::getIsAlarm, reqVO.getIsAlarm())
                .eqIfPresent(InfoDO::getOnline, reqVO.getOnline())
                .eqIfPresent(InfoDO::getDeviceModelId, reqVO.getDeviceModelId())
                .eqIfPresent(InfoDO::getDeviceClassify, reqVO.getDeviceClassify())
                .eqIfPresent(InfoDO::getManufacturer, reqVO.getManufacturer())
                .likeIfPresent(InfoDO::getDeviceModelName, reqVO.getDeviceModelName())
                .eqIfPresent(InfoDO::getInduFacilityInfoId, reqVO.getInduFacilityInfoId())
                .eqIfPresent(InfoDO::getDevicesSource, reqVO.getDevicesSource())
                .eqIfPresent(InfoDO::getAreaId, reqVO.getAreaId())
                .eqIfPresent(InfoDO::getRuralId, reqVO.getRuralId())
                .eqIfPresent(InfoDO::getVillagesAreaId, reqVO.getVillagesAreaId())
                .likeIfPresent(InfoDO::getAreaName, reqVO.getAreaName())
                .likeIfPresent(InfoDO::getRuralName, reqVO.getRuralName())
                .likeIfPresent(InfoDO::getVillagesAreaName, reqVO.getVillagesAreaName())
                .eqIfPresent(InfoDO::getCameraType, reqVO.getCameraType())
                .eqIfPresent(InfoDO::getCameraId, reqVO.getCameraId())
                .eqIfPresent(InfoDO::getAccount, reqVO.getAccount())
                .eqIfPresent(InfoDO::getPassWord, reqVO.getPassWord())
                .eqIfPresent(InfoDO::getPersonnelInfoId, reqVO.getPersonnelInfoId())
                .eqIfPresent(InfoDO::getDevicesTag, reqVO.getDevicesTag())
                .eqIfPresent(InfoDO::getDevicesOnline, reqVO.getDevicesOnline())
                .betweenIfPresent(InfoDO::getCreateTime, reqVO.getCreateTime())
                .eqIfPresent(InfoDO::getSource, reqVO.getSource())
                .eqIfPresent(InfoDO::getSubjectId, reqVO.getSubjectId())
                .orderByDesc(InfoDO::getId));
    }

    default List<InfoDO> selectList(InfoExportReqVO reqVO) {
        return selectList(new LambdaQueryWrapperX<InfoDO>()
                .eqIfPresent(InfoDO::getBaseId, reqVO.getBaseId())
                .eqIfPresent(InfoDO::getTunnelId, reqVO.getTunnelId())
                .eqIfPresent(InfoDO::getFacilitysId, reqVO.getFacilitysId())
                .likeIfPresent(InfoDO::getDeviceName, reqVO.getDeviceName())
                .eqIfPresent(InfoDO::getDeviceSn, reqVO.getDeviceSn())
                .eqIfPresent(InfoDO::getClassify, reqVO.getClassify())
                .eqIfPresent(InfoDO::getDeviceType, reqVO.getDeviceType())
                .likeIfPresent(InfoDO::getDeviceTypeName, reqVO.getDeviceTypeName())
                .eqIfPresent(InfoDO::getBuyer, reqVO.getBuyer())
                .betweenIfPresent(InfoDO::getBuyTime, reqVO.getBuyTime())
                .eqIfPresent(InfoDO::getProductBy, reqVO.getProductBy())
                .eqIfPresent(InfoDO::getProductModel, reqVO.getProductModel())
                .eqIfPresent(InfoDO::getPower, reqVO.getPower())
                .eqIfPresent(InfoDO::getWorkStatus, reqVO.getWorkStatus())
                .eqIfPresent(InfoDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(InfoDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(InfoDO::getParamDeviceIp, reqVO.getParamDeviceIp())
                .eqIfPresent(InfoDO::getParamHttpPort, reqVO.getParamHttpPort())
                .eqIfPresent(InfoDO::getParamDevicePort, reqVO.getParamDevicePort())
                .eqIfPresent(InfoDO::getParamRtspPort, reqVO.getParamRtspPort())
                .likeIfPresent(InfoDO::getParamDeviceUsername, reqVO.getParamDeviceUsername())
                .eqIfPresent(InfoDO::getParamDevicePassword, reqVO.getParamDevicePassword())
                .eqIfPresent(InfoDO::getParamChanelNum, reqVO.getParamChanelNum())
                .eqIfPresent(InfoDO::getParamYsyUrl, reqVO.getParamYsyUrl())
                .eqIfPresent(InfoDO::getParamYsyUrlHd, reqVO.getParamYsyUrlHd())
                .eqIfPresent(InfoDO::getParamStreamType, reqVO.getParamStreamType())
                .eqIfPresent(InfoDO::getOfficeCode, reqVO.getOfficeCode())
                .likeIfPresent(InfoDO::getOfficeName, reqVO.getOfficeName())
                .eqIfPresent(InfoDO::getCompanyCode, reqVO.getCompanyCode())
                .likeIfPresent(InfoDO::getCompanyName, reqVO.getCompanyName())
                .eqIfPresent(InfoDO::getRemarks, reqVO.getRemarks())
                .eqIfPresent(InfoDO::getReviewStatus, reqVO.getReviewStatus())
                .eqIfPresent(InfoDO::getReviewer, reqVO.getReviewer())
                .betweenIfPresent(InfoDO::getReviewDate, reqVO.getReviewDate())
                .eqIfPresent(InfoDO::getReviewContent, reqVO.getReviewContent())
                .eqIfPresent(InfoDO::getIsopen, reqVO.getIsopen())
                .eqIfPresent(InfoDO::getKingViewUrl, reqVO.getKingViewUrl())
                .eqIfPresent(InfoDO::getIsMobile, reqVO.getIsMobile())
                .eqIfPresent(InfoDO::getCorpCode, reqVO.getCorpCode())
                .likeIfPresent(InfoDO::getCorpName, reqVO.getCorpName())
                .betweenIfPresent(InfoDO::getServiceDate, reqVO.getServiceDate())
                .eqIfPresent(InfoDO::getSyncStatus, reqVO.getSyncStatus())
                .eqIfPresent(InfoDO::getIsbeta, reqVO.getIsbeta())
                .eqIfPresent(InfoDO::getOldId, reqVO.getOldId())
                .eqIfPresent(InfoDO::getIotProductKey, reqVO.getIotProductKey())
                .likeIfPresent(InfoDO::getIotDeviceName, reqVO.getIotDeviceName())
                .likeIfPresent(InfoDO::getIotProductName, reqVO.getIotProductName())
                .eqIfPresent(InfoDO::getIotIotId, reqVO.getIotIotId())
                .eqIfPresent(InfoDO::getIsAlarm, reqVO.getIsAlarm())
                .eqIfPresent(InfoDO::getOnline, reqVO.getOnline())
                .eqIfPresent(InfoDO::getDeviceModelId, reqVO.getDeviceModelId())
                .eqIfPresent(InfoDO::getDeviceClassify, reqVO.getDeviceClassify())
                .eqIfPresent(InfoDO::getManufacturer, reqVO.getManufacturer())
                .likeIfPresent(InfoDO::getDeviceModelName, reqVO.getDeviceModelName())
                .eqIfPresent(InfoDO::getInduFacilityInfoId, reqVO.getInduFacilityInfoId())
                .eqIfPresent(InfoDO::getDevicesSource, reqVO.getDevicesSource())
                .eqIfPresent(InfoDO::getAreaId, reqVO.getAreaId())
                .eqIfPresent(InfoDO::getRuralId, reqVO.getRuralId())
                .eqIfPresent(InfoDO::getVillagesAreaId, reqVO.getVillagesAreaId())
                .likeIfPresent(InfoDO::getAreaName, reqVO.getAreaName())
                .likeIfPresent(InfoDO::getRuralName, reqVO.getRuralName())
                .likeIfPresent(InfoDO::getVillagesAreaName, reqVO.getVillagesAreaName())
                .eqIfPresent(InfoDO::getCameraType, reqVO.getCameraType())
                .eqIfPresent(InfoDO::getCameraId, reqVO.getCameraId())
                .eqIfPresent(InfoDO::getAccount, reqVO.getAccount())
                .eqIfPresent(InfoDO::getPassWord, reqVO.getPassWord())
                .eqIfPresent(InfoDO::getPersonnelInfoId, reqVO.getPersonnelInfoId())
                .eqIfPresent(InfoDO::getDevicesTag, reqVO.getDevicesTag())
                .eqIfPresent(InfoDO::getDevicesOnline, reqVO.getDevicesOnline())
                .betweenIfPresent(InfoDO::getCreateTime, reqVO.getCreateTime())
                .eqIfPresent(InfoDO::getSource, reqVO.getSource())
                .eqIfPresent(InfoDO::getSubjectId, reqVO.getSubjectId())
                .orderByDesc(InfoDO::getId));
    }

}
