-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_ticket_package" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "package_name" varchar,
    "package_type" varchar,
    "purchaser" varchar,
    "carrier_id" varchar,
    "number" int,
    "package_money" varchar,
    "service_life" datetime,
    "certigier" varchar,
    "package_status" varchar,
    "remarks" varchar,
    "cover" varchar,
    "content" varchar,
    "regulation" varchar,
    "service_life_type" varchar,
    "package_content" varchar,
    "package_rule" varchar,
    "start_date" datetime,
    "end_date" datetime,
    "ticket_status" varchar,
    "time_num" varchar,
    "time_type" varchar,
    "time_limit_mode" varchar,
    "ticket_type" varchar,
    "status" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    PRIMARY KEY ("id")
) COMMENT '套票表';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_ticket_package";
