-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_loss" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "purchase_id" bigint NOT NULL,
    "purchase_number" varchar NOT NULL,
    "goods_id" bigint NOT NULL,
    "electronic_bill_of_goods_id" bigint NOT NULL,
    "good_sku_id" bigint NOT NULL,
    "goods_name" varchar NOT NULL,
    "packing_specification" varchar NOT NULL,
    "specification_unit" varchar NOT NULL,
    "loss_count" int,
    "loss_weight" int,
    "amount" varchar,
    "manager_id" bigint NOT NULL,
    "manager" varchar NOT NULL,
    "time" datetime,
    "stock_id" bigint NOT NULL,
    "receipt_batch_no" varchar NOT NULL,
    "inventory_record_details_id" bigint NOT NULL,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '损耗表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_loss";
