-- 将该建表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "service_service_adopt_info" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "service_id" varchar,
    "tunnel_id" varchar,
    "adopt_id" varchar,
    "user_id" varchar,
    "adopt_status" varchar,
    "family_id" varchar,
    "plant_crop_id" varchar,
    "plant_crop_num" varchar,
    "basesid" varchar,
    "partitions_id" varchar,
    "carrier_id" varchar,
    "apply_num" varchar,
    "apply_sub_num" varchar,
    "adopt_type" varchar,
    "status" int,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL,
    "source" varchar,
    PRIMARY KEY ("id")
) COMMENT '认养信息表';

-- 将该删表 SQL 语句，添加到 yudao-module-service-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "service_service_adopt_info";
