package cn.acsm.module.transaction.sales.dal.mysql.commoditysku;

import cn.iocoder.yudao.framework.common.pojo.PageResult;
import cn.iocoder.yudao.framework.mybatis.core.mapper.BaseMapperX;
import cn.iocoder.yudao.framework.mybatis.core.query.LambdaQueryWrapperX;
import cn.acsm.module.transaction.sales.controller.admin.commoditysku.vo.*;
import cn.acsm.module.transaction.sales.dal.dataobject.commoditysku.CommoditySkuDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * 商品sku Mapper
 *
 * @author 芋道源码
 */
@Mapper
public interface CommoditySkuMapper extends BaseMapperX<CommoditySkuDO> {

    default PageResult<CommoditySkuDO> selectPage(CommoditySkuPageReqVO reqVO) {
        return selectPage(reqVO, new LambdaQueryWrapperX<CommoditySkuDO>()
                .eqIfPresent(CommoditySkuDO::getCommodityId, reqVO.getCommodityId())
                .eqIfPresent(CommoditySkuDO::getShippingOrderInfoId, reqVO.getShippingOrderInfoId())
                .eqIfPresent(CommoditySkuDO::getStockManagementId, reqVO.getStockManagementId())
                .eqIfPresent(CommoditySkuDO::getVipId, reqVO.getVipId())
                .eqIfPresent(CommoditySkuDO::getSkuCode, reqVO.getSkuCode())
                .eqIfPresent(CommoditySkuDO::getBatch, reqVO.getBatch())
                .eqIfPresent(CommoditySkuDO::getAvailableNum, reqVO.getAvailableNum())
                .eqIfPresent(CommoditySkuDO::getAvailableWeight, reqVO.getAvailableWeight())
                .eqIfPresent(CommoditySkuDO::getSpecNum, reqVO.getSpecNum())
                .eqIfPresent(CommoditySkuDO::getWeightUnit, reqVO.getWeightUnit())
                .eqIfPresent(CommoditySkuDO::getPackageUnit, reqVO.getPackageUnit())
                .eqIfPresent(CommoditySkuDO::getWholesalePrice, reqVO.getWholesalePrice())
                .eqIfPresent(CommoditySkuDO::getRetailPrice, reqVO.getRetailPrice())
                .eqIfPresent(CommoditySkuDO::getTraceStatus, reqVO.getTraceStatus())
                .eqIfPresent(CommoditySkuDO::getSaleState, reqVO.getSaleState())
                .eqIfPresent(CommoditySkuDO::getTag, reqVO.getTag())
                .eqIfPresent(CommoditySkuDO::getSubjectId, reqVO.getSubjectId())
                .eqIfPresent(CommoditySkuDO::getSaleUnit, reqVO.getSaleUnit())
                .likeIfPresent(CommoditySkuDO::getSpecName, reqVO.getSpecName())
                .eqIfPresent(CommoditySkuDO::getTraceBatch, reqVO.getTraceBatch())
                .eqIfPresent(CommoditySkuDO::getTraceType, reqVO.getTraceType())
                .eqIfPresent(CommoditySkuDO::getTraceAddress, reqVO.getTraceAddress())
                .eqIfPresent(CommoditySkuDO::getTraceContact, reqVO.getTraceContact())
                .eqIfPresent(CommoditySkuDO::getTracePhone, reqVO.getTracePhone())
                .likeIfPresent(CommoditySkuDO::getTraceEnterName, reqVO.getTraceEnterName())
                .eqIfPresent(CommoditySkuDO::getTraceLicense, reqVO.getTraceLicense())
                .eqIfPresent(CommoditySkuDO::getCarCode, reqVO.getCarCode())
                .eqIfPresent(CommoditySkuDO::getZslRecordId, reqVO.getZslRecordId())
                .eqIfPresent(CommoditySkuDO::getBoothNo, reqVO.getBoothNo())
                .eqIfPresent(CommoditySkuDO::getBoothNo, reqVO.getBoothNo())
                .eqIfPresent(CommoditySkuDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(CommoditySkuDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(CommoditySkuDO::getMerchantId, reqVO.getMerchantId())
                .eqIfPresent(CommoditySkuDO::getAddress, reqVO.getAddress())
                .betweenIfPresent(CommoditySkuDO::getArriveDate, reqVO.getArriveDate())
                .eqIfPresent(CommoditySkuDO::getProductSpecificationsId, reqVO.getProductSpecificationsId())
                .eqIfPresent(CommoditySkuDO::getAddType, reqVO.getAddType())
                .eqIfPresent(CommoditySkuDO::getSellType, reqVO.getSellType())
                .eqIfPresent(CommoditySkuDO::getProviderId, reqVO.getProviderId())
                .eqIfPresent(CommoditySkuDO::getOldProviderId, reqVO.getOldProviderId())
                .eqIfPresent(CommoditySkuDO::getSourceSkuId, reqVO.getSourceSkuId())
                .eqIfPresent(CommoditySkuDO::getPublicityPrice, reqVO.getPublicityPrice())
                .eqIfPresent(CommoditySkuDO::getPackingType, reqVO.getPackingType())
                .eqIfPresent(CommoditySkuDO::getStockType, reqVO.getStockType())
                .eqIfPresent(CommoditySkuDO::getGoodsPrice, reqVO.getGoodsPrice())
                .eqIfPresent(CommoditySkuDO::getSellingPrice, reqVO.getSellingPrice())
                .eqIfPresent(CommoditySkuDO::getPurchasePrice, reqVO.getPurchasePrice())
                .eqIfPresent(CommoditySkuDO::getAddNum, reqVO.getAddNum())
                .eqIfPresent(CommoditySkuDO::getWeight, reqVO.getWeight())
                .eqIfPresent(CommoditySkuDO::getPluCode, reqVO.getPluCode())
                .eqIfPresent(CommoditySkuDO::getOscommoditySkuThumbnail, reqVO.getOscommoditySkuThumbnail())
                .eqIfPresent(CommoditySkuDO::getPersonnelInfoSlideshow, reqVO.getPersonnelInfoSlideshow())
                .eqIfPresent(CommoditySkuDO::getPersonnelInfoDetailsFigure, reqVO.getPersonnelInfoDetailsFigure())
                .eqIfPresent(CommoditySkuDO::getGrade, reqVO.getGrade())
                .eqIfPresent(CommoditySkuDO::getCreateId, reqVO.getCreateId())
                .eqIfPresent(CommoditySkuDO::getBusinessSellerTag, reqVO.getBusinessSellerTag())
                .eqIfPresent(CommoditySkuDO::getContent, reqVO.getContent())
                .eqIfPresent(CommoditySkuDO::getQuarantineImgs, reqVO.getQuarantineImgs())
                .likeIfPresent(CommoditySkuDO::getPackagingName, reqVO.getPackagingName())
                .likeIfPresent(CommoditySkuDO::getSaleUnitName, reqVO.getSaleUnitName())
                .eqIfPresent(CommoditySkuDO::getAvailablePersonnel, reqVO.getAvailablePersonnel())
                .eqIfPresent(CommoditySkuDO::getCommodityType, reqVO.getCommodityType())
                .eqIfPresent(CommoditySkuDO::getTracea, reqVO.getTracea())
                .eqIfPresent(CommoditySkuDO::getIngredients, reqVO.getIngredients())
                .eqIfPresent(CommoditySkuDO::getCookingMethod, reqVO.getCookingMethod())
                .likeIfPresent(CommoditySkuDO::getSpecificationsName, reqVO.getSpecificationsName())
                .eqIfPresent(CommoditySkuDO::getCollectNum, reqVO.getCollectNum())
                .eqIfPresent(CommoditySkuDO::getStatus, reqVO.getStatus())
                .betweenIfPresent(CommoditySkuDO::getCreateTime, reqVO.getCreateTime())
                .orderByDesc(CommoditySkuDO::getId));
    }

    default List<CommoditySkuDO> selectList(CommoditySkuExportReqVO reqVO) {
        return selectList(new LambdaQueryWrapperX<CommoditySkuDO>()
                .eqIfPresent(CommoditySkuDO::getCommodityId, reqVO.getCommodityId())
                .eqIfPresent(CommoditySkuDO::getShippingOrderInfoId, reqVO.getShippingOrderInfoId())
                .eqIfPresent(CommoditySkuDO::getStockManagementId, reqVO.getStockManagementId())
                .eqIfPresent(CommoditySkuDO::getVipId, reqVO.getVipId())
                .eqIfPresent(CommoditySkuDO::getSkuCode, reqVO.getSkuCode())
                .eqIfPresent(CommoditySkuDO::getBatch, reqVO.getBatch())
                .eqIfPresent(CommoditySkuDO::getAvailableNum, reqVO.getAvailableNum())
                .eqIfPresent(CommoditySkuDO::getAvailableWeight, reqVO.getAvailableWeight())
                .eqIfPresent(CommoditySkuDO::getSpecNum, reqVO.getSpecNum())
                .eqIfPresent(CommoditySkuDO::getWeightUnit, reqVO.getWeightUnit())
                .eqIfPresent(CommoditySkuDO::getPackageUnit, reqVO.getPackageUnit())
                .eqIfPresent(CommoditySkuDO::getWholesalePrice, reqVO.getWholesalePrice())
                .eqIfPresent(CommoditySkuDO::getRetailPrice, reqVO.getRetailPrice())
                .eqIfPresent(CommoditySkuDO::getTraceStatus, reqVO.getTraceStatus())
                .eqIfPresent(CommoditySkuDO::getSaleState, reqVO.getSaleState())
                .eqIfPresent(CommoditySkuDO::getTag, reqVO.getTag())
                .eqIfPresent(CommoditySkuDO::getSubjectId, reqVO.getSubjectId())
                .eqIfPresent(CommoditySkuDO::getSaleUnit, reqVO.getSaleUnit())
                .likeIfPresent(CommoditySkuDO::getSpecName, reqVO.getSpecName())
                .eqIfPresent(CommoditySkuDO::getTraceBatch, reqVO.getTraceBatch())
                .eqIfPresent(CommoditySkuDO::getTraceType, reqVO.getTraceType())
                .eqIfPresent(CommoditySkuDO::getTraceAddress, reqVO.getTraceAddress())
                .eqIfPresent(CommoditySkuDO::getTraceContact, reqVO.getTraceContact())
                .eqIfPresent(CommoditySkuDO::getTracePhone, reqVO.getTracePhone())
                .likeIfPresent(CommoditySkuDO::getTraceEnterName, reqVO.getTraceEnterName())
                .eqIfPresent(CommoditySkuDO::getTraceLicense, reqVO.getTraceLicense())
                .eqIfPresent(CommoditySkuDO::getCarCode, reqVO.getCarCode())
                .eqIfPresent(CommoditySkuDO::getZslRecordId, reqVO.getZslRecordId())
                .eqIfPresent(CommoditySkuDO::getBoothNo, reqVO.getBoothNo())
                .eqIfPresent(CommoditySkuDO::getLatitude, reqVO.getLatitude())
                .eqIfPresent(CommoditySkuDO::getLongitude, reqVO.getLongitude())
                .eqIfPresent(CommoditySkuDO::getMerchantId, reqVO.getMerchantId())
                .eqIfPresent(CommoditySkuDO::getAddress, reqVO.getAddress())
                .betweenIfPresent(CommoditySkuDO::getArriveDate, reqVO.getArriveDate())
                .eqIfPresent(CommoditySkuDO::getProductSpecificationsId, reqVO.getProductSpecificationsId())
                .eqIfPresent(CommoditySkuDO::getAddType, reqVO.getAddType())
                .eqIfPresent(CommoditySkuDO::getSellType, reqVO.getSellType())
                .eqIfPresent(CommoditySkuDO::getProviderId, reqVO.getProviderId())
                .eqIfPresent(CommoditySkuDO::getOldProviderId, reqVO.getOldProviderId())
                .eqIfPresent(CommoditySkuDO::getSourceSkuId, reqVO.getSourceSkuId())
                .eqIfPresent(CommoditySkuDO::getPublicityPrice, reqVO.getPublicityPrice())
                .eqIfPresent(CommoditySkuDO::getPackingType, reqVO.getPackingType())
                .eqIfPresent(CommoditySkuDO::getStockType, reqVO.getStockType())
                .eqIfPresent(CommoditySkuDO::getGoodsPrice, reqVO.getGoodsPrice())
                .eqIfPresent(CommoditySkuDO::getSellingPrice, reqVO.getSellingPrice())
                .eqIfPresent(CommoditySkuDO::getPurchasePrice, reqVO.getPurchasePrice())
                .eqIfPresent(CommoditySkuDO::getAddNum, reqVO.getAddNum())
                .eqIfPresent(CommoditySkuDO::getWeight, reqVO.getWeight())
                .eqIfPresent(CommoditySkuDO::getPluCode, reqVO.getPluCode())
                .eqIfPresent(CommoditySkuDO::getOscommoditySkuThumbnail, reqVO.getOscommoditySkuThumbnail())
                .eqIfPresent(CommoditySkuDO::getPersonnelInfoSlideshow, reqVO.getPersonnelInfoSlideshow())
                .eqIfPresent(CommoditySkuDO::getPersonnelInfoDetailsFigure, reqVO.getPersonnelInfoDetailsFigure())
                .eqIfPresent(CommoditySkuDO::getGrade, reqVO.getGrade())
                .eqIfPresent(CommoditySkuDO::getCreateId, reqVO.getCreateId())
                .eqIfPresent(CommoditySkuDO::getBusinessSellerTag, reqVO.getBusinessSellerTag())
                .eqIfPresent(CommoditySkuDO::getContent, reqVO.getContent())
                .eqIfPresent(CommoditySkuDO::getQuarantineImgs, reqVO.getQuarantineImgs())
                .likeIfPresent(CommoditySkuDO::getPackagingName, reqVO.getPackagingName())
                .likeIfPresent(CommoditySkuDO::getSaleUnitName, reqVO.getSaleUnitName())
                .eqIfPresent(CommoditySkuDO::getAvailablePersonnel, reqVO.getAvailablePersonnel())
                .eqIfPresent(CommoditySkuDO::getCommodityType, reqVO.getCommodityType())
                .eqIfPresent(CommoditySkuDO::getTracea, reqVO.getTracea())
                .eqIfPresent(CommoditySkuDO::getIngredients, reqVO.getIngredients())
                .eqIfPresent(CommoditySkuDO::getCookingMethod, reqVO.getCookingMethod())
                .likeIfPresent(CommoditySkuDO::getSpecificationsName, reqVO.getSpecificationsName())
                .eqIfPresent(CommoditySkuDO::getCollectNum, reqVO.getCollectNum())
                .eqIfPresent(CommoditySkuDO::getStatus, reqVO.getStatus())
                .betweenIfPresent(CommoditySkuDO::getCreateTime, reqVO.getCreateTime())
                .orderByDesc(CommoditySkuDO::getId));
    }

}
