-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_inquiry" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "enquiry_id" varchar NOT NULL,
    "enquiry_name" varchar NOT NULL,
    "provider_id" bigint NOT NULL,
    "provider_name" varchar NOT NULL,
    "post_status" varchar,
    "enquiry_status" varchar,
    "release_time" datetime,
    "read_status" varchar,
    "uid" bigint,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    "user_id" bigint,
    "source_id" bigint,
    PRIMARY KEY ("id")
) COMMENT '采购询价表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_inquiry";
