-- 将该建表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "purchase_details" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "purchase_id" bigint NOT NULL,
    "purchase_number" varchar NOT NULL,
    "goods_id" bigint NOT NULL,
    "goods_name" varchar NOT NULL,
    "packaging_specification_id" bigint,
    "packaging_specification" varchar,
    "unit" varchar NOT NULL,
    "packaging_type" varchar,
    "buy_number" varchar NOT NULL,
    "frequency" varchar,
    "price" varchar,
    "discount" varchar,
    "total" varchar,
    "standard_id" bigint,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '采购单明细表';

-- 将该删表 SQL 语句，添加到 yudao-module-purchase-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "purchase_details";
