-- 将该建表 SQL 语句，添加到 yudao-module-stock-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "stock_inventory_record" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "type" int,
    "warehouse_id" varchar,
    "warehouse_code" varchar,
    "warehouse_name" varchar,
    "inventory_code" varchar,
    "operation_time" datetime,
    "head_id" bigint,
    "head_name" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" varchar NOT NULL,
    "subject_id" varchar NOT NULL,
    "user_id" bigint NOT NULL,
    "source_id" bigint NOT NULL,
    PRIMARY KEY ("id")
) COMMENT '盘点记录表';

-- 将该删表 SQL 语句，添加到 yudao-module-stock-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "stock_inventory_record";
